version: '3.8'
services:
  app:
    container_name: my-bakery-app
    build: .
    ports:
      - "4040:4040"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw

  db:
    image: mysql:5.7
    container_name: my-bakery-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    volumes:
      - ./sql:/var/lib/mysql
      - ./database/build:/docker-entrypoint-initdb.d

volumes:
  dbdata:
